# Generated by Django 6.0.3 on 2026-03-06 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_escolar', models.CharField(max_length=50, unique=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad_nacimiento', models.CharField(max_length=100)),
                ('otras_nacionalidades', models.TextField(blank=True)),
                ('idiomas', models.TextField(blank=True)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais_residencia', models.CharField(max_length=100)),
                ('telefono_habitacion', models.CharField(blank=True, max_length=20)),
                ('telefono_celular', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id_datos_facturacion', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('rif', models.CharField(max_length=20)),
                ('direccion_fiscal', models.TextField()),
                ('correo_facturacion', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Datos de Facturación',
                'verbose_name_plural': 'Datos de Facturación',
                'db_table': 'datos_facturacion',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=8, unique=True, verbose_name='Cédula de Identidad')),
                ('nacionalidad', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], max_length=10, verbose_name='Nacionalidad')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a'), ('U', 'Unión Libre')], max_length=1, verbose_name='Estado Civil')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('celular', models.CharField(max_length=20, verbose_name='Teléfono Celular')),
                ('tel_habitacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Habitación')),
                ('direccion_habitacion', models.TextField(verbose_name='Dirección de Habitación')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('pais_nacimiento', models.CharField(max_length=100, verbose_name='País de Nacimiento')),
                ('ciudad_nacimiento', models.CharField(max_length=100, verbose_name='Ciudad de Nacimiento')),
                ('otras_nacionalidades', models.TextField(blank=True, null=True, verbose_name='Otras Nacionalidades')),
                ('idiomas', models.TextField(blank=True, help_text='Separar por comas', null=True, verbose_name='Idiomas')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religión')),
                ('nivel_educativo', models.CharField(choices=[('basica', 'Educación Básica'), ('media', 'Educación Media'), ('tsp', 'Técnico Superior'), ('lic', 'Licenciatura'), ('ing', 'Ingeniería'), ('postgrado', 'Postgrado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=20, verbose_name='Nivel Educativo')),
                ('profesion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('empresa_trabajo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa donde Trabaja')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('direccion_trabajo', models.TextField(blank=True, null=True, verbose_name='Dirección de Trabajo')),
                ('estado_trabajo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado (Trabajo)')),
                ('pais_trabajo', models.CharField(blank=True, max_length=100, null=True, verbose_name='País (Trabajo)')),
                ('tel_oficina', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Oficina')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_academico', models.CharField(max_length=50)),
                ('grado_cursado', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('COMPLETO', 'Completo'), ('CONFIRMADO', 'Confirmado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago_confirmado', models.DateTimeField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='lidera.alumno')),
                ('id_datos_facturacion', models.ForeignKey(blank=True, db_column='id_datos_facturacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lidera.datosfacturacion')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCupo',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_REVISION', 'En Revisión')], default='PENDIENTE', max_length=20)),
                ('nombres_alumno', models.CharField(max_length=100)),
                ('apellidos_alumno', models.CharField(max_length=100)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('sexo_alumno', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('grado_a_cursar', models.CharField(max_length=50)),
                ('año_escolar', models.CharField(max_length=20)),
                ('colegio_precedencia', models.CharField(max_length=200)),
                ('parentesco_representante', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor Legal'), ('OTRO', 'Otro')], max_length=20)),
                ('id_representante', models.ForeignKey(db_column='id_representante', on_delete=django.db.models.deletion.CASCADE, to='lidera.representante')),
            ],
            options={
                'verbose_name': 'Solicitud de Cupo',
                'verbose_name_plural': 'Solicitudes de Cupo',
                'db_table': 'solicitud_cupo',
            },
        ),
    ]
